### ISSUE TITLE
how to save

### ISSUE THREAD

**Issue by megachurro** [mattbruv/ccsr#12]
how do i save? if i get called on the phone it rests the whole game for me to the beginning

**Comment by mattbruv** [comment]
Right now there is no ability to save the game, and I don't plan on adding that feature. The game is simple and most people probably complete an episode in ~15-30 minutes at most and then won't play it again. I would recommend playing it on a desktop computer and not on mobile, as the experience wasn't designed for mobile.

**Comment by BlazingSalvo** [comment]
I'd like to add that saving was not a feature of the original Shockwave title.
But I guess to better explain what OP is trying to say, this may more be an issue with his mobile browser sleeping/suspended the tab and reloading it OnResume due to system resources. On Android you can save and restore InstanceState as a standard method of Activity, but I've never done actual web development so I don't know if there's anything similar.
